---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipaddrpool
  namespace: metallb
spec:
  addresses:
    - 10.0.0.200-10.0.0.205
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb
