"""
Django settings for pickem project.

Generated by 'django-admin startproject' using Django 3.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import requests

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# https://stackoverflow.com/questions/54784981/django-allauth-google-oauth-redirect-uri-mismatch-error
ACCOUNT_DEFAULT_HTTP_PROTOCOL='https'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Allowed Host(s)
ALLOWED_HOSTS = ['localhost', 'corticolous-unarbitrarily-noel.ngrok-free.dev']

if 'DJANGO_ALLOWED_HOSTS' in os.environ:
    django_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS')
    hosts_list = django_allowed_hosts.split(',')

    for host in hosts_list:
        ALLOWED_HOSTS.append(host)

if 'THIS_POD_IP' in os.environ:
    ALLOWED_HOSTS.append(os.environ["THIS_POD_IP"])

if 'RDS_DB_NAME' in os.environ:
    try:
        EC2_IP = requests.get('http://169.254.169.254/latest/meta-data/local-ipv4').text
        ALLOWED_HOSTS.append(EC2_IP)
    except requests.exceptions.RequestException:
        pass

# CSRF Origins 
CSRF_TRUSTED_ORIGINS = ['https://*.localhost', 'https://*.corticolous-unarbitrarily-noel.ngrok-free.dev']

if 'CSRF_TRUSTED_ORIGINS' in os.environ:
    CSRF_TRUSTED_ORIGINS.append(os.environ["CSRF_TRUSTED_ORIGINS"])


# Application definition
INSTALLED_APPS = [
    'pickem_homepage.apps.PickemHomepageConfig',
    'pickem_api.apps.PickemApiConfig',
    'pickem_superadmin.apps.PickemSuperadminConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_apscheduler',
    'bootstrap5',
    # 'django_ratelimit',  # Disabled for now - enable later when ready
    'allauth',
    'storages',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google'
    # 'dbbackup'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'pickem_homepage.middleware.FamilyLogoUploadHandlerMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'pickem_homepage.middleware.RequireLoginForInternalPagesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Cache configuration for rate limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/tmp/django_cache',
        'TIMEOUT': 300,  # 5 minutes
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Rate limiting configuration
if DEBUG:
    # Development: Disable rate limiting to avoid cache backend issues
    RATELIMIT_ENABLE = False
else:
    # Production: Enable rate limiting
    RATELIMIT_ENABLE = True
    # Use cache for rate limiting (default uses default cache)
    RATELIMIT_USE_CACHE = 'default'
    # View to show when rate limit is exceeded
    RATELIMIT_VIEW = 'pickem_homepage.views.ratelimited'

ROOT_URLCONF = 'pickem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pickem.context_processors.theme_context',
                'pickem.context_processors.family_switcher_context',
                'pickem.context_processors.site_banner_context',
                'pickem.context_processors.footer_stats_context',
                'pickem_superadmin.context_processors.chrome',
            ],
        },
    },
]

WSGI_APPLICATION = 'pickem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

## To get ENV from eb ssh: 
# export $(/opt/elasticbeanstalk/bin/get-config --output YAML environment | sed -r 's/: /=/' | xargs)

if 'RDS_DB_NAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
elif 'DATABASE_HOST' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ['DATABASE_NAME'],
            'USER': os.environ['DATABASE_USER'],
            'PASSWORD': os.environ['DATABASE_PASS'],
            'HOST': os.environ['DATABASE_HOST'],
            'PORT': os.environ['DATABASE_PORT'],
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'pickem',
            'USER': 'postgres',
            'HOST': 'postgresql',
            'PORT': '5432',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

SOCIALACCOUNT_LOGIN_ON_GET=True

SITE_ID = 1

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '').strip()
RESEND_FROM_EMAIL = os.environ.get('RESEND_FROM_EMAIL', '').strip()
RESEND_INVITE_REPLY_TO = os.environ.get('RESEND_INVITE_REPLY_TO', '').strip()
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'http://localhost:8000').strip().rstrip('/')
EMAIL_NOTIFICATION_SAFE_ALLOWLIST_ONLY = (
    os.getenv('EMAIL_NOTIFICATION_SAFE_ALLOWLIST_ONLY', 'True').lower() == 'true'
)
EMAIL_NOTIFICATION_SAFE_ALLOWLIST = [
    email.strip().lower()
    for email in os.environ.get(
        'EMAIL_NOTIFICATION_SAFE_ALLOWLIST',
        'jdagostino2@gmail.com',
    ).split(',')
    if email.strip()
]
# Absolute, publicly-reachable URL to the logo shown in invite emails. Left blank
# by default because production static is served from S3 (URLs can be signed and
# expire, which would break the image in delivered mail); the invite template
# falls back to a styled text wordmark when this is empty. Point it at a stable
# public logo URL to show the image.
INVITE_EMAIL_LOGO_URL = os.environ.get('INVITE_EMAIL_LOGO_URL', '').strip()
WEEKLY_PICKS_EMAIL_LOGO_URL = os.environ.get(
    'WEEKLY_PICKS_EMAIL_LOGO_URL',
    INVITE_EMAIL_LOGO_URL,
).strip()

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# The homepage app owns the current brand assets.  Keep it first in the local
# static-file lookup path so the old project-level copies cannot shadow them
# during development.
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'pickem_homepage', 'static')]

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cache-buster appended to static asset URLs (?v=...). Stable for the life of
# the process so browsers can cache assets, but changes on redeploy/restart.
# Set APP_VERSION in the environment (e.g. the release tag) for a stable
# per-release value across replicas.
import time
STATIC_VERSION = os.getenv('APP_VERSION') or str(int(time.time()))


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = (
    'http://localhost:8081',
)

# Transport / cookie hardening. Gated on DEBUG so local dev over plain HTTP
# still works; in prod (DEBUG=False) TLS is terminated at the Cloudflare edge,
# so the browser always speaks HTTPS and Secure cookies are delivered.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # SECURE_SSL_REDIRECT is intentionally left off: the app runs on plain HTTP
    # behind the Cloudflare TLS edge, so an in-app redirect would loop.
    # Trust the edge/ingress X-Forwarded-Proto so request.is_secure() (and thus
    # request.build_absolute_uri) knows the original request was HTTPS — without
    # it, generated absolute URLs (e.g. invite links in emails) come out as
    # http://. Safe here because all traffic reaches the app through Cloudflare
    # + the nginx ingress, which set this header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

AWS_S3_ADDRESSING_STYLE = "virtual"

# Family-logo delivery is deliberately isolated from the generic AWS
# configuration used by static files and backup jobs.  Production must provide
# every value below through its dedicated ESO-managed Secret; development can
# omit the whole set and use local media storage instead.
_FAMILY_LOGO_AWS_SETTING_NAMES = (
    "FAMILY_LOGO_STORAGE_BUCKET_NAME",
    "FAMILY_LOGO_AWS_S3_REGION_NAME",
    "FAMILY_LOGO_AWS_ACCESS_KEY_ID",
    "FAMILY_LOGO_AWS_SECRET_ACCESS_KEY",
)
for _setting_name in _FAMILY_LOGO_AWS_SETTING_NAMES:
    globals()[_setting_name] = os.environ.get(_setting_name, "")

_family_logo_values = tuple(globals()[name] for name in _FAMILY_LOGO_AWS_SETTING_NAMES)
if any(_family_logo_values) and not all(_family_logo_values):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "Family logo S3 storage requires all FAMILY_LOGO_* credential settings."
    )

try:
    FAMILY_LOGO_AWS_QUERYSTRING_EXPIRE = int(
        os.environ.get("FAMILY_LOGO_AWS_QUERYSTRING_EXPIRE", "300")
    )
except ValueError as error:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "FAMILY_LOGO_AWS_QUERYSTRING_EXPIRE must be a positive integer."
    ) from error
if FAMILY_LOGO_AWS_QUERYSTRING_EXPIRE <= 0:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "FAMILY_LOGO_AWS_QUERYSTRING_EXPIRE must be a positive integer."
    )

if 'AWS_STORAGE_BUCKET_NAME' in os.environ:
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']
    AWS_S3_REGION_NAME = os.environ['AWS_S3_REGION_NAME']

    AWS_S3_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
    AWS_S3_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']

# --- Application logging -> superadmin console -------------------------------
# App loggers are captured at INFO so the pipeline's own activity is visible in
# the console ("I feel blind"); everything else at WARNING to avoid per-request
# noise. Both are env-tunable. The DB handler writes SuperAdminLogEntry rows;
# the console handler keeps stdout intact for `kubectl logs`.
SUPERADMIN_LOG_APP_LEVEL = os.environ.get('SUPERADMIN_LOG_APP_LEVEL', 'INFO')
SUPERADMIN_LOG_ROOT_LEVEL = os.environ.get('SUPERADMIN_LOG_ROOT_LEVEL', 'WARNING')
LOG_RETENTION_DAYS = int(os.environ.get('LOG_RETENTION_DAYS', '14'))
LOG_MAX_ROWS = int(os.environ.get('LOG_MAX_ROWS', '10000'))

# 'django.job' is the per-step pipeline logger namespace (django.job.<step>).
# It must be listed explicitly at app level — under 'django' it would otherwise
# inherit the root WARNING threshold and INFO step output would be dropped.
_SUPERADMIN_APP_LOGGERS = (
    'pickem_api', 'pickem_homepage', 'pickem_superadmin', 'django.job',
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
        'superadmin_db': {'class': 'pickem_superadmin.logging.DatabaseLogHandler'},
    },
    'root': {
        'handlers': ['console', 'superadmin_db'],
        'level': SUPERADMIN_LOG_ROOT_LEVEL,
    },
    'loggers': {
        name: {
            'handlers': ['console', 'superadmin_db'],
            'level': SUPERADMIN_LOG_APP_LEVEL,
            'propagate': False,
        }
        for name in _SUPERADMIN_APP_LOGGERS
    },
}
