---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "family-pickem.fullname" . }}-envvars
data:
{{- range $key, $value := .Values.app.env }}
  {{- $value := b64enc $value -}}
  {{- println $key ": " $value | nindent 2 }}
{{- end }}
