# Generated by Django 4.0.2 on 2022-08-18 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
