# Generated by Django 4.0.2 on 2025-09-23 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pickem_homepage', '0002_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title/message', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional additional description')),
                ('banner_type', models.CharField(choices=[('success', 'Success (Green)'), ('info', 'Info (Blue)'), ('warning', 'Warning (Yellow)'), ('danger', 'Danger (Red)')], default='success', help_text='Visual style of the banner', max_length=20)),
                ('icon', models.CharField(default='fas fa-trophy', help_text="Font Awesome icon class (e.g., 'fas fa-trophy', 'fas fa-info-circle')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this banner should be displayed')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this banner should start being displayed')),
                ('end_date', models.DateTimeField(blank=True, help_text='When this banner should stop being displayed (leave blank for indefinite)', null=True)),
                ('show_close_button', models.BooleanField(default=True, help_text='Whether users can dismiss this banner')),
                ('priority', models.IntegerField(default=1, help_text='Banner priority (higher numbers shown first if multiple active)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Banner',
                'verbose_name_plural': 'Site Banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
