# Generated by Django 4.0.2 on 2026-06-28 18:49

from django.db import migrations, models
import django.db.models.deletion


LEGACY_FAMILY_SLUG = 'legacy-family-league'
LEGACY_FAMILY_NAME = 'Legacy Family League'


def _ensure_membership(FamilyMembership, family, user):
    membership, created = FamilyMembership.objects.get_or_create(
        family=family,
        user=user,
        defaults={'role': 'member', 'status': 'active'},
    )
    if created:
        return membership

    updates = []
    if membership.status != 'active':
        membership.status = 'active'
        updates.append('status')
    if updates:
        membership.save(update_fields=updates)
    return membership


def _collect_active_message_board_user_ids(User, *models_to_scan):
    user_ids = set()
    for Model in models_to_scan:
        for user_id in Model.objects.exclude(user_id__isnull=True).values_list('user_id', flat=True).iterator():
            user_ids.add(user_id)
    if not user_ids:
        return set()
    return set(
        User.objects.filter(id__in=user_ids, is_active=True).values_list('id', flat=True)
    )


def backfill_homepage_family_scope(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Family = apps.get_model('pickem_api', 'Family')
    FamilyMembership = apps.get_model('pickem_api', 'FamilyMembership')
    MessageBoardPost = apps.get_model('pickem_homepage', 'MessageBoardPost')
    MessageBoardComment = apps.get_model('pickem_homepage', 'MessageBoardComment')
    MessageBoardVote = apps.get_model('pickem_homepage', 'MessageBoardVote')

    legacy_family, _ = Family.objects.get_or_create(
        slug=LEGACY_FAMILY_SLUG,
        defaults={'name': LEGACY_FAMILY_NAME, 'status': 'active'},
    )

    MessageBoardPost.objects.filter(family__isnull=True).update(family=legacy_family)

    comments_without_family = MessageBoardComment.objects.filter(family__isnull=True).select_related('post')
    for comment in comments_without_family.iterator():
        if comment.post_id and comment.post.family_id:
            comment.family_id = comment.post.family_id
            comment.save(update_fields=['family'])

    votes_without_family = MessageBoardVote.objects.filter(family__isnull=True).select_related('post', 'comment')
    for vote in votes_without_family.iterator():
        family_id = None
        if vote.post_id and vote.post.family_id:
            family_id = vote.post.family_id
        elif vote.comment_id and vote.comment.family_id:
            family_id = vote.comment.family_id
        if family_id:
            vote.family_id = family_id
            vote.save(update_fields=['family'])

    active_user_ids = _collect_active_message_board_user_ids(
        User,
        MessageBoardPost,
        MessageBoardComment,
        MessageBoardVote,
    )
    for user in User.objects.filter(id__in=active_user_ids, is_active=True).order_by('date_joined', 'id'):
        _ensure_membership(FamilyMembership, legacy_family, user)


def clear_homepage_family_scope(apps, schema_editor):
    MessageBoardPost = apps.get_model('pickem_homepage', 'MessageBoardPost')
    MessageBoardComment = apps.get_model('pickem_homepage', 'MessageBoardComment')
    MessageBoardVote = apps.get_model('pickem_homepage', 'MessageBoardVote')

    MessageBoardVote.objects.filter(family__isnull=False).update(family=None)
    MessageBoardComment.objects.filter(family__isnull=False).update(family=None)
    MessageBoardPost.objects.filter(family__isnull=False).update(family=None)


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0074_add_legacy_pool_scope'),
        ('pickem_homepage', '0004_messageboardpost_messageboardcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboardcomment',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_board_comments', to='pickem_api.family'),
        ),
        migrations.AddField(
            model_name='messageboardpost',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_board_posts', to='pickem_api.family'),
        ),
        migrations.AddField(
            model_name='messageboardvote',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_board_votes', to='pickem_api.family'),
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='family',
            field=models.ForeignKey(blank=True, help_text='Optional family scope; blank keeps the banner site-wide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='pickem_api.family'),
        ),
        migrations.AddIndex(
            model_name='messageboardcomment',
            index=models.Index(fields=['family', 'created_at'], name='comment_family_created_idx'),
        ),
        migrations.AddIndex(
            model_name='messageboardpost',
            index=models.Index(fields=['family', 'is_active', 'created_at'], name='post_family_active_idx'),
        ),
        migrations.AddIndex(
            model_name='messageboardvote',
            index=models.Index(fields=['family', 'created_at'], name='vote_family_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sitebanner',
            index=models.Index(fields=['family', 'is_active', 'created_at'], name='banner_family_active_idx'),
        ),
        migrations.RunPython(backfill_homepage_family_scope, clear_homepage_family_scope),
    ]
