# Generated by Django 4.0.2 on 2026-07-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickem_api', '0074_add_legacy_pool_scope'),
        ('pickem_homepage', '0005_add_family_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Markdown source. Raw HTML is never rendered.')),
                ('source', models.CharField(choices=[('commissioner', 'Commissioner'), ('ai_weekly_summary', 'AI weekly summary')], default='commissioner', max_length=32)),
                ('generation_reference', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_publications', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='pickem_api.family')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='pickem_api.pool')),
            ],
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='familypublication',
            index=models.Index(fields=['family', 'pool', 'is_published', 'published_at'], name='publication_lobby_idx'),
        ),
        migrations.AddConstraint(
            model_name='familypublication',
            constraint=models.CheckConstraint(check=models.Q(source__in=['commissioner', 'ai_weekly_summary']), name='publication_source_valid'),
        ),
    ]
