# Generated by Django 4.2.30 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_homepage', '0006_familypublication'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='familypublication',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_published=True),
                fields=('pool',),
                name='one_published_publication_per_pool',
            ),
        ),
    ]
