# Generated by Django 4.2.30 on 2026-07-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0092_merge_family_logo_and_picks_lock_mode'),
        ('pickem_homepage', '0007_one_published_publication_per_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWeeklySummaryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('week', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disabled', 'Disabled'), ('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pickem_api.family')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pickem_api.pool')),
                ('publication', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_summary_run', to='pickem_homepage.familypublication')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='aiweeklysummaryrun',
            index=models.Index(fields=['pool', 'season', 'week', 'created_at'], name='ai_summary_pool_week_idx'),
        ),
    ]
