# Generated by Django 4.2.30 on 2026-07-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_homepage', '0010_ai_summary_run_publication_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familypublication',
            name='source',
            field=models.CharField(choices=[('commissioner', 'Commissioner'), ('ai_weekly_summary', 'Sideline')], default='commissioner', max_length=32),
        ),
    ]
