# Generated by Django 5.2.16 on 2026-10-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_homepage', '0012_ai_recap_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiweeklysummaryrun',
            name='review_issues',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiweeklysummaryrun',
            name='review_status',
            field=models.CharField(blank=True, choices=[('passed', 'Passed review'), ('revised', 'Revised, then passed'), ('failed', 'Published with open issues'), ('error', 'Reviewer unavailable'), ('skipped', 'Not reviewed')], max_length=16),
        ),
    ]
