apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # External Secrets Operator Helm chart
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: "0.19.2"
      helm:
        valueFiles:
          - $values/infra/external-secrets/values.yaml
    # Values from Git
    - repoURL: git@github.com:jimdaga/family-pickem.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
