# Generated by Django 4.2.30 on 2026-07-14 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_blocked', 'User blocked'), ('user_unblocked', 'User unblocked'), ('user_profile_updated', 'User profile updated'), ('family_updated', 'Family updated'), ('pool_settings_updated', 'Pool settings updated'), ('team_updated', 'Team updated'), ('season_updated', 'Current season updated'), ('banner_published', 'Site banner published'), ('job_queued', 'Pipeline job queued'), ('data_repair', 'Data repair action')], max_length=50)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superadmin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Superadmin audit log',
                'verbose_name_plural': 'Superadmin audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sa_audit_created_idx'), models.Index(fields=['action'], name='sa_audit_action_idx')],
            },
        ),
    ]
