# Generated by Django 4.2.30 on 2026-07-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadminauditlog',
            name='action',
            field=models.CharField(choices=[('user_blocked', 'User blocked'), ('user_unblocked', 'User unblocked'), ('user_profile_updated', 'User profile updated'), ('family_updated', 'Family updated'), ('pool_settings_updated', 'Pool settings updated'), ('team_updated', 'Team updated'), ('season_updated', 'Current season updated'), ('banner_published', 'Site banner published'), ('job_queued', 'Pipeline job queued'), ('data_repair', 'Data repair action'), ('schedule_updated', 'Job schedule updated')], max_length=50),
        ),
    ]
