# Generated by Django 4.2.30 on 2026-07-16 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_superadmin', '0002_alter_superadminauditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                ('level_no', models.PositiveSmallIntegerField(default=0)),
                ('logger_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('pathname', models.CharField(blank=True, max_length=255, null=True)),
                ('lineno', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level_no', '-timestamp'], name='sa_log_level_ts_idx'), models.Index(fields=['-timestamp'], name='sa_log_ts_idx')],
            },
        ),
    ]
