# Generated by Django 4.2.30 on 2026-07-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_superadmin', '0003_superadminlogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadminauditlog',
            name='action',
            field=models.CharField(choices=[('user_blocked', 'User blocked'), ('user_unblocked', 'User unblocked'), ('user_profile_updated', 'User profile updated'), ('family_updated', 'Family updated'), ('pool_settings_updated', 'Pool settings updated'), ('team_updated', 'Team updated'), ('season_updated', 'Current season updated'), ('banner_published', 'Site banner published'), ('job_queued', 'Pipeline job queued'), ('data_repair', 'Data repair action'), ('schedule_updated', 'Job schedule updated'), ('email_settings_updated', 'Email settings updated'), ('email_test_sent', 'Email test sent')], max_length=50),
        ),
        migrations.CreateModel(
            name='EmailProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.CharField(default='default', max_length=20, unique=True)),
                ('provider', models.CharField(choices=[('resend', 'Resend')], default='resend', max_length=30)),
                ('invites_enabled', models.BooleanField(default=False)),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('reply_to_email', models.CharField(blank=True, default='', max_length=255)),
                ('api_key_ciphertext', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email provider settings',
                'verbose_name_plural': 'Email provider settings',
            },
        ),
    ]
