# Generated by Django 4.2.30 on 2026-07-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_superadmin', '0004_alter_superadminauditlog_action_emailprovidersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_key', models.CharField(choices=[('weekly_picks_available', 'Weekly picks available')], max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('weekday', models.PositiveSmallIntegerField(default=2)),
                ('hour', models.PositiveSmallIntegerField(default=9)),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('timezone_name', models.CharField(default='America/New_York', max_length=64)),
                ('rollout_mode', models.CharField(choices=[('allowlist', 'Allowlist only'), ('all_enabled_users', 'All eligible users')], default='allowlist', max_length=50)),
                ('allowlist_emails', models.TextField(blank=True, default='jdagostino2@gmail.com', help_text='Comma-separated email allowlist for safe rollout and testing.')),
                ('family_link_strategy', models.CharField(choices=[('earliest_membership', 'Earliest joined family')], default='earliest_membership', max_length=50)),
                ('last_sent_season', models.IntegerField(blank=True, null=True)),
                ('last_sent_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email notification campaign',
                'verbose_name_plural': 'Email notification campaigns',
                'ordering': ['campaign_key'],
            },
        ),
        migrations.AlterField(
            model_name='superadminauditlog',
            name='action',
            field=models.CharField(choices=[('user_blocked', 'User blocked'), ('user_unblocked', 'User unblocked'), ('user_profile_updated', 'User profile updated'), ('family_updated', 'Family updated'), ('pool_settings_updated', 'Pool settings updated'), ('team_updated', 'Team updated'), ('season_updated', 'Current season updated'), ('banner_published', 'Site banner published'), ('job_queued', 'Pipeline job queued'), ('data_repair', 'Data repair action'), ('schedule_updated', 'Job schedule updated'), ('email_settings_updated', 'Email settings updated'), ('email_test_sent', 'Email test sent'), ('email_campaign_updated', 'Email campaign updated'), ('email_campaign_sent', 'Email campaign sent'), ('email_preview_sent', 'Email preview sent')], max_length=50),
        ),
    ]
