# Generated by Django 4.2.30 on 2026-07-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_superadmin', '0005_emailnotificationcampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadminlogentry',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='superadminlogentry',
            name='run_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='superadminlogentry',
            index=models.Index(fields=['run_id'], name='sa_log_run_idx'),
        ),
    ]
