# Generated by Django 5.2.16 on 2026-07-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_superadmin', '0007_alter_superadminauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadminauditlog',
            name='action',
            field=models.CharField(choices=[('user_blocked', 'User blocked'), ('user_unblocked', 'User unblocked'), ('user_profile_updated', 'User profile updated'), ('family_updated', 'Family updated'), ('family_force_deleted', 'Family force-deleted'), ('pool_settings_updated', 'Pool settings updated'), ('team_updated', 'Team updated'), ('season_updated', 'Current season updated'), ('banner_published', 'Site banner published'), ('banner_deactivated', 'Site banner deactivated'), ('job_queued', 'Pipeline job queued'), ('data_repair', 'Data repair action'), ('schedule_updated', 'Job schedule updated'), ('email_settings_updated', 'Email settings updated'), ('email_test_sent', 'Email test sent'), ('email_campaign_updated', 'Email campaign updated'), ('email_campaign_sent', 'Email campaign sent'), ('email_preview_sent', 'Email preview sent')], max_length=50),
        ),
    ]
