# Generated by Django 4.2.30 on 2026-07-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_superadmin', '0007_alter_superadminauditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.CharField(default='default', max_length=20, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('retries', models.PositiveSmallIntegerField(default=2)),
                ('max_runs_per_pool_week', models.PositiveSmallIntegerField(default=3)),
                ('api_key_ciphertext', models.TextField(blank=True, default='', editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI provider settings',
                'verbose_name_plural': 'AI provider settings',
            },
        ),
        migrations.AlterField(
            model_name='superadminauditlog',
            name='action',
            field=models.CharField(choices=[('user_blocked', 'User blocked'), ('user_unblocked', 'User unblocked'), ('user_profile_updated', 'User profile updated'), ('family_updated', 'Family updated'), ('family_force_deleted', 'Family force-deleted'), ('pool_settings_updated', 'Pool settings updated'), ('team_updated', 'Team updated'), ('season_updated', 'Current season updated'), ('banner_published', 'Site banner published'), ('job_queued', 'Pipeline job queued'), ('data_repair', 'Data repair action'), ('schedule_updated', 'Job schedule updated'), ('email_settings_updated', 'Email settings updated'), ('email_test_sent', 'Email test sent'), ('email_campaign_updated', 'Email campaign updated'), ('email_campaign_sent', 'Email campaign sent'), ('email_preview_sent', 'Email preview sent'), ('ai_settings_updated', 'AI settings updated')], max_length=50),
        ),
    ]
