# Generated by Django 4.2.30 on 2026-07-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_superadmin', '0009_alter_superadminauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationcampaign',
            name='campaign_key',
            field=models.CharField(choices=[('weekly_picks_available', 'Weekly picks available'), ('missed_picks_reminder', 'Missed picks reminder')], max_length=50, unique=True),
        ),
    ]
