# Generated by Django 5.2.16 on 2026-10-03 03:25

from django.db import migrations, models


# Models we know predate reasoning-effort support (or that recaps used before
# it was configurable). Moving them forward keeps the first post-deploy run
# from sending `reasoning.effort` to a model that rejects it.
LEGACY_MODELS = ('gpt-4o-mini', 'gpt-5.6-luna')


def move_to_reasoning_model(apps, schema_editor):
    AIProviderSettings = apps.get_model('pickem_superadmin', 'AIProviderSettings')
    for settings_obj in AIProviderSettings.objects.all():
        if settings_obj.model in LEGACY_MODELS:
            settings_obj.model = 'gpt-6-luna'
        # High reasoning plus a fact-check pass routinely runs 30-60s per call.
        settings_obj.timeout_seconds = max(settings_obj.timeout_seconds, 120)
        settings_obj.save(update_fields=['model', 'timeout_seconds'])


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_superadmin', '0010_alter_emailnotificationcampaign_campaign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='reasoning_effort',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'Extra high'), ('max', 'Max')], default='high', max_length=10),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='review_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='review_reasoning_effort',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'Extra high'), ('max', 'Max')], default='high', max_length=10),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='model',
            field=models.CharField(default='gpt-6-luna', max_length=100),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.RunPython(move_to_reasoning_model, migrations.RunPython.noop),
    ]
