# Generated by Django 5.2.16 on 2026-10-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_superadmin', '0010_alter_emailnotificationcampaign_campaign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='reasoning_effort',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'Extra high'), ('max', 'Max')], default='high', max_length=10),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='review_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='review_reasoning_effort',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'Extra high'), ('max', 'Max')], default='high', max_length=10),
        ),
    ]
