# Generated by Django 4.0.2 on 2022-08-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pickem_api', '0002_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250)),
                ('startTimestamp', models.DateTimeField()),
                ('scoreHomeAwaySlug', models.CharField(max_length=10)),
                ('scoreAwayHomeSlug', models.CharField(max_length=10)),
                ('gameWinner', models.IntegerField()),
                ('statusType', models.CharField(max_length=250)),
                ('statusTitle', models.CharField(max_length=250)),
                ('homeTeamId', models.IntegerField()),
                ('homeTeamSlug', models.CharField(max_length=250)),
                ('homeTeamName', models.CharField(max_length=250)),
                ('homeTeamScore', models.IntegerField()),
                ('awayTeamId', models.IntegerField()),
                ('awayTeamSlug', models.CharField(max_length=250)),
                ('awayTeamName', models.CharField(max_length=250)),
                ('awayTeamScore', models.IntegerField()),
            ],
        ),
    ]
