# Generated by Django 4.0.2 on 2022-08-18 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='gameAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='gameUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
