# Generated by Django 4.0.2 on 2022-08-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0004_schedule_gameadded_schedule_gameupdated'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesAndScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250)),
                ('gameWeek', models.CharField(max_length=250)),
                ('startTimestamp', models.DateTimeField()),
                ('gameWinner', models.IntegerField()),
                ('statusType', models.CharField(max_length=250)),
                ('statusTitle', models.CharField(max_length=250)),
                ('homeTeamId', models.IntegerField()),
                ('homeTeamSlug', models.CharField(max_length=250)),
                ('homeTeamName', models.CharField(max_length=250)),
                ('homeTeamScore', models.IntegerField()),
                ('awayTeamId', models.IntegerField()),
                ('awayTeamSlug', models.CharField(max_length=250)),
                ('awayTeamName', models.CharField(max_length=250)),
                ('awayTeamScore', models.IntegerField()),
                ('gameAdded', models.DateTimeField(auto_now_add=True)),
                ('gameUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
