# Generated by Django 4.0.2 on 2022-08-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0006_gamesandscores_gameyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesandscores',
            name='gameyear',
            field=models.CharField(max_length=4),
        ),
    ]
