# Generated by Django 4.0.2 on 2022-08-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0007_alter_gamesandscores_gameyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesandscores',
            name='competition',
            field=models.CharField(default='nfl-preseason', max_length=250),
        ),
    ]
