# Generated by Django 4.0.2 on 2022-08-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0008_gamesandscores_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesandscores',
            name='competition',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='gamesandscores',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
