# Generated by Django 4.0.2 on 2022-08-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0009_alter_gamesandscores_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesandscores',
            name='gameWinner',
            field=models.CharField(max_length=4),
        ),
    ]
