# Generated by Django 4.0.2 on 2022-08-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0010_alter_gamesandscores_gamewinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesandscores',
            name='gameWinner',
            field=models.CharField(max_length=250),
        ),
    ]
