# Generated by Django 4.0.2 on 2022-08-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0011_alter_gamesandscores_gamewinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWeeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekNumber', models.IntegerField()),
                ('competition', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
