# Generated by Django 4.0.2 on 2022-08-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0012_gameweeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameweeks',
            name='date',
            field=models.DateField(),
        ),
    ]
