# Generated by Django 4.0.2 on 2022-08-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0013_alter_gameweeks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameweeks',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
