# Generated by Django 4.0.2 on 2022-08-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0015_alter_gameweeks_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesandscores',
            options={'ordering': ['-startTimestamp']},
        ),
    ]
