# Generated by Django 4.0.2 on 2022-08-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0016_alter_gamesandscores_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesandscores',
            options={'ordering': ['startTimestamp']},
        ),
    ]
