# Generated by Django 4.0.2 on 2022-08-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0017_alter_gamesandscores_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=254)),
                ('slug', models.SlugField(max_length=250)),
                ('competition', models.CharField(max_length=250)),
                ('gameWeek', models.CharField(max_length=2)),
                ('gameyear', models.CharField(max_length=4)),
                ('pick_game_id', models.IntegerField()),
                ('homeTeamSlug', models.CharField(max_length=250)),
                ('awayTeamSlug', models.CharField(max_length=250)),
                ('pickAdded', models.DateTimeField(auto_now_add=True)),
                ('pickUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['gameWeek'],
            },
        ),
    ]
