# Generated by Django 4.0.2 on 2022-08-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0018_gamepicks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamepicks',
            old_name='awayTeamSlug',
            new_name='pick',
        ),
        migrations.RemoveField(
            model_name='gamepicks',
            name='homeTeamSlug',
        ),
    ]
