# Generated by Django 4.0.2 on 2022-08-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0019_rename_awayteamslug_gamepicks_pick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepicks',
            name='userID',
            field=models.CharField(default='jimbo', max_length=250),
        ),
    ]
