# Generated by Django 4.0.2 on 2022-08-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0020_gamepicks_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepicks',
            name='userID',
            field=models.CharField(max_length=250),
        ),
    ]
