# Generated by Django 4.0.2 on 2022-08-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0021_alter_gamepicks_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepicks',
            name='pick_points',
            field=models.IntegerField(default=0),
        ),
    ]
