# Generated by Django 4.0.2 on 2022-08-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0024_remove_gamepicks_pick_win_gamepicks_pick_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepicks',
            name='pick_points',
        ),
        migrations.AddField(
            model_name='gamepicks',
            name='pick_correct',
            field=models.BooleanField(default=False),
        ),
    ]
