# Generated by Django 4.0.2 on 2022-09-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0026_alter_gamepicks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesandscores',
            name='gameScored',
            field=models.BooleanField(default=False),
        ),
    ]
