# Generated by Django 4.0.2 on 2022-09-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0027_gamesandscores_gamescored'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesandscores',
            name='awayTeamPeriod1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesandscores',
            name='awayTeamPeriod2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesandscores',
            name='awayTeamPeriod3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesandscores',
            name='awayTeamPeriod4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesandscores',
            name='homeTeamPeriod1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesandscores',
            name='homeTeamPeriod2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesandscores',
            name='homeTeamPeriod3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesandscores',
            name='homeTeamPeriod4',
            field=models.IntegerField(default=0),
        ),
    ]
