# Generated by Django 4.0.2 on 2022-09-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0028_gamesandscores_awayteamperiod1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teamNameId', models.IntegerField()),
                ('teamNameSlug', models.CharField(max_length=250)),
                ('teamNameName', models.CharField(max_length=250)),
            ],
        ),
    ]
