# Generated by Django 4.0.2 on 2022-09-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0029_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='teamLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='teamWins',
            field=models.IntegerField(default=0),
        ),
    ]
