# Generated by Django 4.0.2 on 2022-09-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0031_remove_teams_teamnameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepicks',
            name='tieBreaker',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
