# Generated by Django 4.0.2 on 2022-09-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0032_gamepicks_tiebreaker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamepicks',
            old_name='tieBreaker',
            new_name='tieBreakerScore',
        ),
        migrations.AddField(
            model_name='gamepicks',
            name='tieBreakerGame',
            field=models.BooleanField(default=False),
        ),
    ]
