# Generated by Django 4.0.2 on 2022-09-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0033_rename_tiebreaker_gamepicks_tiebreakerscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepicks',
            name='tieBreakerScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
