# Generated by Django 4.0.2 on 2022-09-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0034_alter_gamepicks_tiebreakerscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepicks',
            name='tieBreakerGame',
        ),
        migrations.AddField(
            model_name='gamesandscores',
            name='tieBreakerGame',
            field=models.BooleanField(default=False),
        ),
    ]
