# Generated by Django 4.0.2 on 2022-09-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0035_remove_gamepicks_tiebreakergame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepicks',
            name='competition',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='gamepicks',
            name='gameWeek',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='gamepicks',
            name='gameyear',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='gamepicks',
            name='pick',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='gamepicks',
            name='pick_correct',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gamepicks',
            name='pick_game_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamepicks',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='gamepicks',
            name='userEmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='gamepicks',
            name='userID',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
