# Generated by Django 4.0.2 on 2022-09-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0036_alter_gamepicks_competition_alter_gamepicks_gameweek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesandscores',
            name='awayTeamPeriod1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesandscores',
            name='awayTeamPeriod2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesandscores',
            name='awayTeamPeriod3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesandscores',
            name='awayTeamPeriod4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesandscores',
            name='awayTeamScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesandscores',
            name='homeTeamPeriod1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesandscores',
            name='homeTeamPeriod2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesandscores',
            name='homeTeamPeriod3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesandscores',
            name='homeTeamPeriod4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesandscores',
            name='homeTeamScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
