# Generated by Django 4.0.2 on 2022-09-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0038_userpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpoints',
            name='userID',
        ),
    ]
