# Generated by Django 4.0.2 on 2022-09-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0039_remove_userpoints_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='userID',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
