# Generated by Django 4.0.2 on 2022-09-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0040_userpoints_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepicks',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
