# Generated by Django 4.0.2 on 2022-09-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0041_gamepicks_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='teamTies',
            field=models.IntegerField(default=0),
        ),
    ]
