# Generated by Django 4.0.2 on 2022-09-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0043_userpoints_week_10_bonus_userpoints_week_11_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepicks',
            name='tieBreakerYards',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
