# Generated by Django 4.0.2 on 2022-09-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0045_gamesandscores_awayteamperiodot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesandscores',
            name='gameWinner',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
