# Generated by Django 4.0.2 on 2022-09-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0046_alter_gamesandscores_gamewinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='teamLogo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
