# Generated by Django 4.0.2 on 2023-08-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0047_teams_teamlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweeks',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
