# Generated by Django 4.0.2 on 2023-08-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0048_gameweeks_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesandscores',
            name='gameseason',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
