# Generated by Django 4.0.2 on 2023-08-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0049_gamesandscores_gameseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepicks',
            name='gameseason',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='gameseason',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
