# Generated by Django 4.0.2 on 2023-08-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0050_gamepicks_gameseason_userpoints_gameseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='gameseason',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
