# Generated by Django 4.0.2 on 2023-08-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0052_seasonpoints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seasonPoints',
        ),
    ]
