# Generated by Django 4.0.2 on 2024-09-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0054_userseasonpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='userStats',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('userEmail', models.EmailField(blank=True, max_length=254)),
                ('userID', models.CharField(blank=True, max_length=250)),
                ('weeksWonTotal', models.IntegerField(blank=True, null=True)),
                ('weeksWonSeason', models.IntegerField(blank=True, null=True)),
                ('correctPickPercent', models.IntegerField(blank=True, null=True)),
                ('correctPickTotal', models.IntegerField(blank=True, null=True)),
                ('totalPicks', models.IntegerField(blank=True, null=True)),
                ('mostPickedTeam', models.CharField(blank=True, max_length=250)),
                ('leastPickedTeam', models.CharField(blank=True, max_length=250)),
                ('seasonsWon', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
