# Generated by Django 4.0.2 on 2024-09-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0055_userstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstats',
            old_name='correctPickPercent',
            new_name='correctPickTotalSeason',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='correctPickTotal',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='leastPickedTeam',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='mostPickedTeam',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='totalPicks',
        ),
        migrations.AddField(
            model_name='userstats',
            name='correctPickTotalTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='leastPickedSeason',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='userstats',
            name='leastPickedTotal',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='userstats',
            name='mostPickedSeason',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='userstats',
            name='mostPickedTotal',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='userstats',
            name='pickPercentTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='totalPicksSeason',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='totalPicksTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
