# Generated by Django 4.0.2 on 2024-09-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0056_rename_correctpickpercent_userstats_correctpicktotalseason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='pickPercentSeason',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
