# Generated by Django 4.0.2 on 2024-10-25 03:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0058_alter_userstats_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
