# Generated by Django 4.0.2 on 2024-10-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0059_alter_userstats_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='correctPickTotalSeason',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='correctPickTotalTotal',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='leastPickedSeason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='leastPickedTotal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='mostPickedSeason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='mostPickedTotal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='pickPercentSeason',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='pickPercentTotal',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='seasonsWon',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='totalPicksSeason',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='totalPicksTotal',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='weeksWonSeason',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='weeksWonTotal',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
    ]
