# Generated by Django 4.0.2 on 2025-07-24 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickem_api', '0061_currentseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, help_text='A short personal tagline or bio', max_length=200, null=True)),
                ('favorite_team', models.CharField(blank=True, help_text="User's favorite NFL team slug", max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('dark_mode', models.BooleanField(default=False, help_text='Use dark mode theme')),
                ('private_profile', models.BooleanField(default=False, help_text='Make profile private to other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
