# Generated by Django 4.0.2 on 2025-07-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0063_alter_userstats_leastpickedseason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='missedPicksSeason',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='missedPicksTotal',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
    ]
