# Generated by Django 4.0.2 on 2025-07-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0064_userstats_missedpicksseason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='perfectWeeksSeason',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='perfectWeeksTotal',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
    ]
