# Generated by Django 4.0.2 on 2025-09-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0066_add_betting_weather_venue_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentseason',
            name='display_name',
            field=models.CharField(blank=True, help_text="User-friendly season name (e.g., '2025-2026')", max_length=20, null=True),
        ),
    ]
