# Generated by Django 4.0.2 on 2025-09-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0067_currentseason_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_commissioner',
            field=models.BooleanField(default=False, help_text='User has commissioner privileges'),
        ),
    ]
