# Generated by Django 4.0.2 on 2025-12-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0068_userprofile_is_commissioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='alternateColor',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
