# Generated by Django 4.0.2 on 2025-12-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0069_teams_alternatecolor_teams_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesandscores',
            name='broadcast',
            field=models.CharField(blank=True, help_text='TV network broadcasting the game (e.g., CBS, FOX, ESPN)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamesandscores',
            name='gamecastUrl',
            field=models.URLField(blank=True, help_text='ESPN Gamecast URL for the game', max_length=500, null=True),
        ),
    ]
