# Generated by Django 4.0.2 on 2025-12-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0070_gamesandscores_broadcast_gamesandscores_gamecasturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseasonpoints',
            name='current_rank',
            field=models.IntegerField(blank=True, help_text='Current ranking position (handles ties)', null=True),
        ),
    ]
