# Generated by Django 4.0.2 on 2026-06-28 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickem_api', '0072_rename_statustype_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Family display name', max_length=200)),
                ('slug', models.SlugField(help_text='Stable family URL slug', max_length=80, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Family lifecycle status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['name', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pool display name', max_length=200)),
                ('slug', models.SlugField(help_text='Stable pool slug within a family', max_length=80)),
                ('season', models.IntegerField(help_text='Season in YYZZ format, e.g. 2526')),
                ('competition', models.CharField(default='nfl', help_text='Competition identifier', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', help_text='Pool lifecycle status', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default pool for this family')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pools', to='pickem_api.family')),
            ],
            options={
                'verbose_name': 'Pool',
                'verbose_name_plural': 'Pools',
                'ordering': ['family__name', 'season', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picks_lock_at_kickoff', models.BooleanField(default=True, help_text='Lock picks when each game starts')),
                ('allow_tiebreaker', models.BooleanField(default=True, help_text='Allow tiebreaker predictions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='pickem_api.pool')),
            ],
            options={
                'verbose_name': 'Pool Settings',
                'verbose_name_plural': 'Pool Settings',
                'ordering': ['pool__family__name', 'pool__name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', help_text='Family-level role', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Membership lifecycle status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='pickem_api.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Membership',
                'verbose_name_plural': 'Family Memberships',
                'ordering': ['family__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='Hashed invite code', max_length=128, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', help_text='Role assigned when invite is accepted', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_family_invitations', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='pickem_api.family')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='pickem_api.pool')),
            ],
            options={
                'verbose_name': 'Family Invitation',
                'verbose_name_plural': 'Family Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('invitation_created', 'Invitation created'), ('invitation_revoked', 'Invitation revoked'), ('membership_created', 'Membership created'), ('membership_updated', 'Membership updated'), ('pool_settings_updated', 'Pool settings updated'), ('manual_pick_updated', 'Manual pick updated'), ('week_winner_updated', 'Week winner updated')], max_length=50)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='pickem_api.family')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pickem_api.pool')),
            ],
            options={
                'verbose_name': 'Family Audit Log',
                'verbose_name_plural': 'Family Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['slug'], name='family_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'inactive'])), name='family_status_valid'),
        ),
        migrations.AddIndex(
            model_name='pool',
            index=models.Index(fields=['family', 'slug', 'status'], name='pool_family_slug_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(fields=('family', 'slug'), name='unique_pool_family_slug'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'inactive', 'archived'])), name='pool_status_valid'),
        ),
        migrations.AddIndex(
            model_name='familymembership',
            index=models.Index(fields=['family', 'user', 'status'], name='member_family_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='familymembership',
            constraint=models.UniqueConstraint(fields=('family', 'user'), name='unique_family_membership_user'),
        ),
        migrations.AddConstraint(
            model_name='familymembership',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['owner', 'admin', 'member'])), name='family_membership_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='familymembership',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'inactive'])), name='family_membership_status_valid'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['code_hash'], name='invitation_code_hash_idx'),
        ),
        migrations.AddConstraint(
            model_name='familyinvitation',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['owner', 'admin', 'member'])), name='family_invitation_role_valid'),
        ),
        migrations.AddIndex(
            model_name='familyauditlog',
            index=models.Index(fields=['family', 'created_at'], name='audit_family_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='familyauditlog',
            constraint=models.CheckConstraint(check=models.Q(('action__in', ['invitation_created', 'invitation_revoked', 'membership_created', 'membership_updated', 'pool_settings_updated', 'manual_pick_updated', 'week_winner_updated'])), name='family_audit_log_action_valid'),
        ),
    ]
