# Generated by Django 4.0.2 on 2026-06-28 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0073_domain_schema_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepicks',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_picks', to='pickem_api.pool'),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_user_points', to='pickem_api.pool'),
        ),
        migrations.AddField(
            model_name='userseasonpoints',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_points', to='pickem_api.pool'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_stats', to='pickem_api.pool'),
        ),
        migrations.AddIndex(
            model_name='gamepicks',
            index=models.Index(fields=['pool', 'gameseason'], name='gp_pool_season_idx'),
        ),
        migrations.AddIndex(
            model_name='gamepicks',
            index=models.Index(fields=['pool', 'gameseason', 'gameWeek'], name='gp_pool_season_week_idx'),
        ),
        migrations.AddIndex(
            model_name='gamepicks',
            index=models.Index(fields=['pool', 'userID'], name='gp_pool_userid_idx'),
        ),
        migrations.AddIndex(
            model_name='userpoints',
            index=models.Index(fields=['pool', 'gameseason'], name='up_pool_season_idx'),
        ),
        migrations.AddIndex(
            model_name='userpoints',
            index=models.Index(fields=['pool', 'userID'], name='up_pool_userid_idx'),
        ),
        migrations.AddIndex(
            model_name='userseasonpoints',
            index=models.Index(fields=['pool', 'gameseason'], name='usp_pool_season_idx'),
        ),
        migrations.AddIndex(
            model_name='userseasonpoints',
            index=models.Index(fields=['pool', 'userID'], name='usp_pool_userid_idx'),
        ),
        migrations.AddIndex(
            model_name='userstats',
            index=models.Index(fields=['pool', 'userID'], name='us_pool_userid_idx'),
        ),
    ]
