# Generated by Django 4.0.2 on 2026-06-28 18:39

from django.db import migrations, models
import django.db.models.deletion


LEGACY_FAMILY_SLUG = 'legacy-family-league'
LEGACY_FAMILY_NAME = 'Legacy Family League'
FALLBACK_LEGACY_SEASON = 2024
# When no currentSeason row exists, use the deterministic fallback slug below
# with season=2024 so the migration is stable in empty/new environments.
FALLBACK_POOL_SLUG = 'legacy-pickem'


def _get_model(apps, app_label, model_name):
    try:
        return apps.get_model(app_label, model_name)
    except LookupError:
        return None


def _get_legacy_pool_defaults(CurrentSeason):
    season_obj = CurrentSeason.objects.exclude(season__isnull=True).order_by('-id').first()
    if season_obj:
        season = season_obj.season
        return season, f'{season}-pickem', f'{season} Pickem'
    return FALLBACK_LEGACY_SEASON, FALLBACK_POOL_SLUG, 'Legacy Pickem'


def _active_user_for_reference(User, uid=None, user_id=None, user_email=None):
    candidates = User.objects.filter(is_active=True)
    if uid:
        user = candidates.filter(id=uid).order_by('date_joined', 'id').first()
        if user:
            return user
    if user_id:
        user = candidates.filter(username=user_id).order_by('date_joined', 'id').first()
        if user:
            return user
    if user_email:
        user = candidates.filter(email=user_email).order_by('date_joined', 'id').first()
        if user:
            return user
    return None


def _collect_competition_user_ids(apps, User):
    user_ids = set()

    GamePicks = apps.get_model('pickem_api', 'GamePicks')
    for row in GamePicks.objects.values('uid', 'userID', 'userEmail').iterator():
        user = _active_user_for_reference(
            User,
            uid=row.get('uid'),
            user_id=row.get('userID'),
            user_email=row.get('userEmail'),
        )
        if user:
            user_ids.add(user.id)

    for model_name in ['userSeasonPoints', 'userPoints', 'userStats']:
        Model = apps.get_model('pickem_api', model_name)
        for row in Model.objects.values('userID', 'userEmail').iterator():
            user = _active_user_for_reference(
                User,
                user_id=row.get('userID'),
                user_email=row.get('userEmail'),
            )
            if user:
                user_ids.add(user.id)

    return user_ids


def _collect_message_board_user_ids(apps):
    user_ids = set()
    for model_name in ['MessageBoardPost', 'MessageBoardComment', 'MessageBoardVote']:
        Model = _get_model(apps, 'pickem_homepage', model_name)
        if not Model:
            continue
        for user_id in Model.objects.exclude(user_id__isnull=True).values_list('user_id', flat=True).iterator():
            user_ids.add(user_id)
    return user_ids


def _ensure_membership(FamilyMembership, family, user, role):
    membership, created = FamilyMembership.objects.get_or_create(
        family=family,
        user=user,
        defaults={'role': role, 'status': 'active'},
    )
    if created:
        return membership

    role_rank = {'member': 1, 'admin': 2, 'owner': 3}
    updates = []
    if membership.status != 'active':
        membership.status = 'active'
        updates.append('status')
    if role_rank[role] > role_rank.get(membership.role, 0):
        membership.role = role
        updates.append('role')
    if updates:
        membership.save(update_fields=updates)
    return membership


def backfill_legacy_pool_scope(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Family = apps.get_model('pickem_api', 'Family')
    Pool = apps.get_model('pickem_api', 'Pool')
    PoolSettings = apps.get_model('pickem_api', 'PoolSettings')
    FamilyMembership = apps.get_model('pickem_api', 'FamilyMembership')
    UserProfile = apps.get_model('pickem_api', 'UserProfile')
    CurrentSeason = apps.get_model('pickem_api', 'currentSeason')

    family, _ = Family.objects.get_or_create(
        slug=LEGACY_FAMILY_SLUG,
        defaults={'name': LEGACY_FAMILY_NAME, 'status': 'active'},
    )
    season, pool_slug, pool_name = _get_legacy_pool_defaults(CurrentSeason)
    pool, _ = Pool.objects.get_or_create(
        family=family,
        slug=pool_slug,
        defaults={
            'name': pool_name,
            'season': season,
            'competition': 'nfl',
            'status': 'active',
            'is_default': True,
        },
    )
    PoolSettings.objects.get_or_create(pool=pool)

    active_superusers = list(
        User.objects.filter(is_active=True, is_superuser=True).order_by('date_joined', 'id')
    )
    for user in active_superusers:
        _ensure_membership(FamilyMembership, family, user, 'owner')

    commissioner_user_ids = list(
        UserProfile.objects.filter(
            is_commissioner=True,
            user__is_active=True,
            user__is_superuser=False,
        )
        .order_by('user__date_joined', 'user__id')
        .values_list('user_id', flat=True)
    )
    commissioner_users = list(
        User.objects.filter(id__in=commissioner_user_ids).order_by('date_joined', 'id')
    )

    owner_assigned_from_commissioner = False
    if not active_superusers and commissioner_users:
        _ensure_membership(FamilyMembership, family, commissioner_users[0], 'owner')
        owner_assigned_from_commissioner = True

    for user in commissioner_users[1 if owner_assigned_from_commissioner else 0:]:
        _ensure_membership(FamilyMembership, family, user, 'admin')

    competition_user_ids = _collect_competition_user_ids(apps, User)
    message_board_user_ids = _collect_message_board_user_ids(apps)

    if not active_superusers and not commissioner_users:
        fallback_user = (
            User.objects.filter(
                id__in=competition_user_ids | message_board_user_ids,
                is_active=True,
            )
            .order_by('date_joined', 'id')
            .first()
        )
        if fallback_user:
            _ensure_membership(FamilyMembership, family, fallback_user, 'owner')

    competition_users = User.objects.filter(
        id__in=competition_user_ids,
        is_active=True,
    ).order_by('date_joined', 'id')
    for user in competition_users:
        _ensure_membership(FamilyMembership, family, user, 'member')

    for model_name in ['GamePicks', 'userSeasonPoints', 'userPoints', 'userStats']:
        Model = apps.get_model('pickem_api', model_name)
        Model.objects.filter(pool__isnull=True).update(pool=pool)


def clear_legacy_pool_scope(apps, schema_editor):
    for model_name in ['GamePicks', 'userSeasonPoints', 'userPoints', 'userStats']:
        Model = apps.get_model('pickem_api', model_name)
        Model.objects.filter(pool__isnull=False).update(pool=None)


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0073_domain_schema_foundation'),
        ('pickem_homepage', '0004_messageboardpost_messageboardcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepicks',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_picks', to='pickem_api.pool'),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_user_points', to='pickem_api.pool'),
        ),
        migrations.AddField(
            model_name='userseasonpoints',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_points', to='pickem_api.pool'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_stats', to='pickem_api.pool'),
        ),
        migrations.AddIndex(
            model_name='gamepicks',
            index=models.Index(fields=['pool', 'gameseason'], name='gp_pool_season_idx'),
        ),
        migrations.AddIndex(
            model_name='gamepicks',
            index=models.Index(fields=['pool', 'gameseason', 'gameWeek'], name='gp_pool_season_week_idx'),
        ),
        migrations.AddIndex(
            model_name='gamepicks',
            index=models.Index(fields=['pool', 'userID'], name='gp_pool_userid_idx'),
        ),
        migrations.AddIndex(
            model_name='userpoints',
            index=models.Index(fields=['pool', 'gameseason'], name='up_pool_season_idx'),
        ),
        migrations.AddIndex(
            model_name='userpoints',
            index=models.Index(fields=['pool', 'userID'], name='up_pool_userid_idx'),
        ),
        migrations.AddIndex(
            model_name='userseasonpoints',
            index=models.Index(fields=['pool', 'gameseason'], name='usp_pool_season_idx'),
        ),
        migrations.AddIndex(
            model_name='userseasonpoints',
            index=models.Index(fields=['pool', 'userID'], name='usp_pool_userid_idx'),
        ),
        migrations.AddIndex(
            model_name='userstats',
            index=models.Index(fields=['pool', 'userID'], name='us_pool_userid_idx'),
        ),
        migrations.RunPython(backfill_legacy_pool_scope, clear_legacy_pool_scope),
    ]
