# Generated by Django 4.0.2 on 2026-06-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0074_add_legacy_pool_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='correctPickTotalSeason',
            field=models.IntegerField(blank=True, db_column='correctpicktotalseason', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='correctPickTotalTotal',
            field=models.IntegerField(blank=True, db_column='correctpicktotaltotal', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='missedPicksSeason',
            field=models.IntegerField(blank=True, db_column='missedpicksseason', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='missedPicksTotal',
            field=models.IntegerField(blank=True, db_column='missedpickstotal', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='perfectWeeksSeason',
            field=models.IntegerField(blank=True, db_column='perfectweeksseason', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='perfectWeeksTotal',
            field=models.IntegerField(blank=True, db_column='perfectweekstotal', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='pickPercentSeason',
            field=models.IntegerField(blank=True, db_column='pickpercentseason', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='pickPercentTotal',
            field=models.IntegerField(blank=True, db_column='pickpercenttotal', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='seasonsWon',
            field=models.IntegerField(blank=True, db_column='seasonswon', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='totalPicksSeason',
            field=models.IntegerField(blank=True, db_column='totalpicksseason', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='totalPicksTotal',
            field=models.IntegerField(blank=True, db_column='totalpickstotal', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='weeksWonSeason',
            field=models.IntegerField(blank=True, db_column='weekswonseason', null=True),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='weeksWonTotal',
            field=models.IntegerField(blank=True, db_column='weekswontotal', null=True),
        ),
    ]
