# Generated by Django 4.0.2 on 2026-07-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0075_alter_userstats_correctpicktotalseason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='logo_url',
            field=models.CharField(blank=True, help_text='URL or static path to family logo (e.g. /static/images/logo.png or https://...)', max_length=500, null=True),
        ),
    ]
