# Generated by Django 4.2.20 on 2026-07-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0076_add_family_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolsettings',
            name='entry_fee_amount',
            field=models.PositiveIntegerField(default=0, help_text='Entry fee per player, in whole dollars'),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='entry_fee_enabled',
            field=models.BooleanField(default=False, help_text='Whether this pool collects an entry fee'),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='perfect_week_bonus_enabled',
            field=models.BooleanField(default=False, help_text='Award a bonus for picking every game correctly in a week'),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='perfect_week_bonus_points',
            field=models.PositiveSmallIntegerField(default=3, help_text='Bonus points for a perfect week'),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='primary_tiebreaker',
            field=models.CharField(choices=[('total_score', 'Closest total score'), ('total_score_no_over', 'Closest total score without going over'), ('combined_yards', 'Closest combined yards')], default='total_score', help_text='First tiebreaker used to settle weekly ties', max_length=32),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='secondary_tiebreaker',
            field=models.CharField(choices=[('combined_yards', 'Closest combined yards'), ('total_score', 'Closest total score'), ('split_points', 'Split the points'), ('coin_flip', 'Coin flip')], default='combined_yards', help_text='Second tiebreaker if the primary is also tied', max_length=32),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='tie_points',
            field=models.PositiveSmallIntegerField(default=0, help_text='Points awarded when a picked game ends in a tie'),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='weekly_winner_points',
            field=models.PositiveSmallIntegerField(default=2, help_text='Bonus points awarded to the weekly winner'),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='win_points',
            field=models.PositiveSmallIntegerField(default=1, help_text='Points awarded per correct pick'),
        ),
    ]
