# Generated by Django 4.2.20 on 2026-07-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0077_poolsettings_entry_fee_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolsettings',
            name='perfect_week_bonus_points',
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='include_playoffs',
            field=models.BooleanField(default=False, help_text='Continue the pool through the playoffs (scoring logic coming later)'),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='late_join_policy',
            field=models.CharField(choices=[('open', 'Members can join all season'), ('lock_after_week_1', 'Entries lock after Week 1')], default='open', help_text='Whether members can join after the season starts', max_length=32),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='missed_pick_policy',
            field=models.CharField(choices=[('zero_points', 'No points for missed picks'), ('auto_home', 'Auto-pick the home team'), ('auto_favorite', 'Auto-pick the favorite')], default='zero_points', help_text="What happens when a member doesn't submit a pick", max_length=32),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='payout_structure',
            field=models.CharField(choices=[('winner_takes_all', '1st place takes the whole pool'), ('ninety_ten', '1st gets 90%, 2nd gets 10%'), ('seventy_twenty_ten', '1st 70%, 2nd 20%, 3rd 10%'), ('second_gets_fee_back', '1st takes the pool, 2nd gets their entry fee back')], default='winner_takes_all', help_text='How the pot is split when an entry fee is collected', max_length=32),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='perfect_week_bonus_amount',
            field=models.PositiveIntegerField(default=10, help_text='Perfect week bonus, in whole dollars'),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='pick_type',
            field=models.CharField(choices=[('straight_up', 'Straight up (pick the winner)'), ('against_spread', 'Against the spread (coming soon)')], default='straight_up', help_text='How picks are made (against-the-spread is not yet available)', max_length=32),
        ),
        migrations.AlterField(
            model_name='poolsettings',
            name='perfect_week_bonus_enabled',
            field=models.BooleanField(default=False, help_text='Award a cash bonus for picking every game correctly in a week'),
        ),
    ]
