# Generated by Django 4.2.20 on 2026-07-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0078_remove_poolsettings_perfect_week_bonus_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Commissioner'), ('admin', 'Admin'), ('member', 'Member')], default='member', help_text='Role assigned when invite is accepted', max_length=20),
        ),
        migrations.AlterField(
            model_name='familymembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Commissioner'), ('admin', 'Admin'), ('member', 'Member')], default='member', help_text='Family-level role', max_length=20),
        ),
    ]
