# Generated by Django 4.2.30 on 2026-07-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0079_alter_familyinvitation_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepicks',
            name='auto_pick',
            field=models.BooleanField(default=False, help_text="Pick was generated by the pool's missed-pick policy, not the user"),
        ),
    ]
