# Generated by Django 4.2.30 on 2026-07-14 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickem_api', '0081_teams_logo_contrast_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked_at',
            field=models.DateTimeField(blank=True, help_text='When this user was blocked site-wide', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blocked_by',
            field=models.ForeignKey(blank=True, help_text='Superadmin who blocked this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blocked_reason',
            field=models.TextField(blank=True, default='', help_text='Why this user was blocked'),
        ),
    ]
