# Generated by Django 4.2.30 on 2026-07-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0082_userprofile_blocked_at_userprofile_blocked_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentseason',
            options={'ordering': ['id']},
        ),
    ]
