# Generated by Django 4.2.30 on 2026-07-16 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0083_alter_currentseason_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('interval_minutes', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['job_id'],
            },
        ),
    ]
