# Generated by Django 4.2.30 on 2026-07-16 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0084_scheduledjobconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningJobMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]
