# Generated by Django 4.2.30 on 2026-07-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0085_runningjobmarker'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyinvitation',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text="Optional recipient email that must match the redeemer's account", max_length=254, null=True),
        ),
    ]
