# Generated by Django 4.2.30 on 2026-07-17 13:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0086_familyinvitation_recipient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjobconfig',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_id', models.CharField(db_index=True, max_length=100)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='running', max_length=10)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_id', '-started_at'], name='jobrun_job_started_idx'), models.Index(fields=['-started_at'], name='jobrun_started_idx')],
            },
        ),
    ]
