# Generated by Django 4.2.30 on 2026-07-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0087_scheduledjobconfig_last_run_at_jobrun'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='familyauditlog',
            name='family_audit_log_action_valid',
        ),
        migrations.AlterField(
            model_name='familyauditlog',
            name='action',
            field=models.CharField(choices=[('invitation_created', 'Invitation created'), ('invitation_revoked', 'Invitation revoked'), ('membership_created', 'Membership created'), ('membership_updated', 'Membership updated'), ('pool_settings_updated', 'Pool settings updated'), ('manual_pick_updated', 'Manual pick updated'), ('week_winner_updated', 'Week winner updated'), ('family_status_updated', 'Family status updated')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='familyauditlog',
            constraint=models.CheckConstraint(check=models.Q(('action__in', ['invitation_created', 'invitation_revoked', 'membership_created', 'membership_updated', 'pool_settings_updated', 'manual_pick_updated', 'week_winner_updated', 'family_status_updated'])), name='family_audit_log_action_valid'),
        ),
    ]
