# Generated by Django 4.2.30 on 2026-07-18

from django.db import migrations, models
import pickem_api.models
import pickem_api.storage


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0089_rename_seasoned_default_pool_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='family',
            name='logo',
            field=models.ImageField(
                blank=True,
                help_text='Server-generated canonical family logo.',
                null=True,
                storage=pickem_api.storage.FamilyLogoStorage(),
                upload_to=pickem_api.models.family_logo_upload_to,
            ),
        ),
    ]
