# Generated by Django 4.2.30 on 2026-07-18 19:35

from django.db import migrations, models


def backfill_lock_mode(apps, schema_editor):
    PoolSettings = apps.get_model('pickem_api', 'PoolSettings')
    PoolSettings.objects.filter(picks_lock_at_kickoff=False).update(picks_lock_mode='sunday_1pm')
    PoolSettings.objects.filter(picks_lock_at_kickoff=True).update(picks_lock_mode='kickoff')


def reverse_lock_mode(apps, schema_editor):
    PoolSettings = apps.get_model('pickem_api', 'PoolSettings')
    PoolSettings.objects.filter(picks_lock_mode='sunday_1pm').update(picks_lock_at_kickoff=False)
    PoolSettings.objects.filter(picks_lock_mode='kickoff').update(picks_lock_at_kickoff=True)


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0089_rename_seasoned_default_pool_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolsettings',
            name='picks_lock_mode',
            field=models.CharField(choices=[('kickoff', 'Lock each game at kickoff'), ('sunday_1pm', 'Weekly cutoff — Sunday 1PM ET')], default='kickoff', help_text='When picks lock: each game at kickoff, or a weekly Sunday 1PM ET cutoff', max_length=16),
        ),
        migrations.RunPython(backfill_lock_mode, reverse_lock_mode),
    ]
