# Generated by Django 4.2.30 on 2026-07-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0090_picks_lock_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolsettings',
            name='picks_lock_at_kickoff',
        ),
    ]
