# Generated by Django 4.2.30 on 2026-07-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0090_replace_family_logo_url'),
        ('pickem_api', '0091_remove_picks_lock_at_kickoff'),
    ]

    operations = []
