# Generated by Django 4.2.30 on 2026-07-20 02:24

from django.db import migrations, models


def dedupe_season_points(apps, schema_editor):
    """Drop duplicate (pool, userID, gameseason) rows, keeping the most
    recently updated one, so the unique constraints can be applied.

    Streams via .values()+.iterator() and issues a single bulk delete for
    the duplicates, rather than loading every row into memory and issuing
    one DELETE per duplicate.
    """
    userSeasonPoints = apps.get_model('pickem_api', 'userSeasonPoints')
    seen = set()
    duplicate_ids = []
    rows = (
        userSeasonPoints.objects.order_by('-playerUpdated', '-id')
        .values('id', 'pool_id', 'userID', 'gameseason')
        .iterator()
    )
    for row in rows:
        key = (row['pool_id'], row['userID'], row['gameseason'])
        if key in seen:
            duplicate_ids.append(row['id'])
        else:
            seen.add(key)
    if duplicate_ids:
        userSeasonPoints.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0092_merge_family_logo_and_picks_lock_mode'),
    ]

    operations = [
        migrations.RunPython(dedupe_season_points, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='userseasonpoints',
            constraint=models.UniqueConstraint(fields=('pool', 'userID', 'gameseason'), name='usp_unique_pool_user_season'),
        ),
        migrations.AddConstraint(
            model_name='userseasonpoints',
            constraint=models.UniqueConstraint(condition=models.Q(('pool__isnull', True)), fields=('userID', 'gameseason'), name='usp_unique_nullpool_user_season'),
        ),
    ]
