# Generated by Django 5.2.16 on 2026-07-20 02:26

from django.db import migrations, models


def dedupe_user_stats(apps, schema_editor):
    """Drop duplicate (pool, userID) stats rows, keeping the lowest id (the
    row `update_stats._upsert` would have kept), so the constraints apply."""
    userStats = apps.get_model('pickem_api', 'userStats')
    seen = set()
    for row in userStats.objects.order_by('id'):
        key = (row.pool_id, row.userID)
        if key in seen:
            row.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0093_userseasonpoints_unique'),
    ]

    operations = [
        migrations.RunPython(dedupe_user_stats, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.UniqueConstraint(fields=('pool', 'userID'), name='us_unique_pool_user'),
        ),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.UniqueConstraint(condition=models.Q(('pool__isnull', True)), fields=('userID',), name='us_unique_nullpool_user'),
        ),
    ]
