# Generated by Django 4.2.30 on 2026-07-20 02:26

from django.db import migrations, models


def dedupe_user_stats(apps, schema_editor):
    """Drop duplicate (pool, userID) stats rows, keeping the lowest id (the
    row `update_stats._upsert` would have kept), so the constraints apply.

    Streams via .values()+.iterator() and issues a single bulk delete for
    the duplicates, rather than loading every row into memory and issuing
    one DELETE per duplicate.
    """
    userStats = apps.get_model('pickem_api', 'userStats')
    seen = set()
    duplicate_ids = []
    rows = (
        userStats.objects.order_by('id')
        .values('id', 'pool_id', 'userID')
        .iterator()
    )
    for row in rows:
        key = (row['pool_id'], row['userID'])
        if key in seen:
            duplicate_ids.append(row['id'])
        else:
            seen.add(key)
    if duplicate_ids:
        userStats.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0093_userseasonpoints_unique'),
    ]

    operations = [
        migrations.RunPython(dedupe_user_stats, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.UniqueConstraint(fields=('pool', 'userID'), name='us_unique_pool_user'),
        ),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.UniqueConstraint(condition=models.Q(('pool__isnull', True)), fields=('userID',), name='us_unique_nullpool_user'),
        ),
    ]
