# Generated by Django 4.2.30 on 2026-07-20 02:37

import django.db.models.deletion
from django.db import migrations, models


def dedupe_game_picks(apps, schema_editor):
    """Drop duplicate (pool, userID, pick_game_id) picks, keeping the most
    recently updated row, so the unique constraints can be applied.

    Streams via .values()+.iterator() and issues a single bulk delete for
    the duplicates, rather than loading every row into memory and issuing
    one DELETE per duplicate — GamePicks is the largest of these tables.
    """
    GamePicks = apps.get_model('pickem_api', 'GamePicks')
    seen = set()
    duplicate_ids = []
    rows = (
        GamePicks.objects.order_by('-pickUpdated', '-id')
        .values('id', 'pool_id', 'userID', 'pick_game_id')
        .iterator()
    )
    for row in rows:
        key = (row['pool_id'], row['userID'], row['pick_game_id'])
        if key in seen:
            duplicate_ids.append(row['id'])
        else:
            seen.add(key)
    if duplicate_ids:
        GamePicks.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0094_userstats_unique'),
    ]

    operations = [
        migrations.RunPython(dedupe_game_picks, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='gamepicks',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_picks', to='pickem_api.pool'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_user_points', to='pickem_api.pool'),
        ),
        migrations.AlterField(
            model_name='userseasonpoints',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='season_points', to='pickem_api.pool'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_stats', to='pickem_api.pool'),
        ),
        migrations.AddConstraint(
            model_name='gamepicks',
            constraint=models.UniqueConstraint(fields=('pool', 'userID', 'pick_game_id'), name='gp_unique_pool_user_game'),
        ),
        migrations.AddConstraint(
            model_name='gamepicks',
            constraint=models.UniqueConstraint(condition=models.Q(('pool__isnull', True)), fields=('userID', 'pick_game_id'), name='gp_unique_nullpool_user_game'),
        ),
    ]
