# Generated by Django 4.2.30 on 2026-07-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0095_pool_protect_and_pick_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username_confirmed',
            field=models.BooleanField(default=True, help_text='User has chosen their own username (vs the auto-generated signup one)'),
        ),
    ]
