# Generated by Django 4.2.30 on 2026-07-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0096_userprofile_username_confirmed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamesandscores',
            index=models.Index(fields=['gameseason', 'gameWeek', 'competition'], name='games_season_week_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesandscores',
            index=models.Index(fields=['gameseason', 'statusType'], name='games_season_status_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesandscores',
            index=models.Index(fields=['startTimestamp'], name='games_start_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='teams',
            index=models.Index(fields=['teamNameSlug'], name='teams_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='teams',
            index=models.Index(fields=['gameseason'], name='teams_gameseason_idx'),
        ),
    ]
