# Generated by Django 5.2.16 on 2026-09-09 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0097_gamesandscores_games_season_week_comp_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poolsettings',
            name='payment_tracking_enabled',
            field=models.BooleanField(default=False, help_text='Track which members have paid the entry fee. Opt-in: while off, no payment page and no lobby notice appear anywhere.'),
        ),
        migrations.AlterField(
            model_name='familyauditlog',
            name='action',
            field=models.CharField(choices=[('invitation_created', 'Invitation created'), ('invitation_revoked', 'Invitation revoked'), ('membership_created', 'Membership created'), ('membership_updated', 'Membership updated'), ('pool_settings_updated', 'Pool settings updated'), ('manual_pick_updated', 'Manual pick updated'), ('week_winner_updated', 'Week winner updated'), ('payment_updated', 'Payment status updated'), ('family_status_updated', 'Family status updated')], max_length=50),
        ),
        migrations.CreateModel(
            name='PoolMemberPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameseason', models.IntegerField(help_text='Season in YYZZ form.')),
                ('paid', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_marked', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_payments', to='pickem_api.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pool', 'user'],
                'indexes': [models.Index(fields=['pool', 'gameseason', 'paid'], name='payment_pool_season_idx')],
                'unique_together': {('pool', 'user', 'gameseason')},
            },
        ),
    ]
