# Generated by Django 5.2.16 on 2026-09-09 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0098_poolsettings_payment_tracking_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='familyauditlog',
            name='family_audit_log_action_valid',
        ),
        migrations.AddConstraint(
            model_name='familyauditlog',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['invitation_created', 'invitation_revoked', 'membership_created', 'membership_updated', 'pool_settings_updated', 'manual_pick_updated', 'week_winner_updated', 'family_status_updated', 'payment_updated'])), name='family_audit_log_action_valid'),
        ),
    ]
