# Generated by Django 5.2.16 on 2026-09-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0099_remove_familyauditlog_family_audit_log_action_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolsettings',
            name='ai_summaries_enabled',
            field=models.BooleanField(default=False, help_text="Run Sideline's AI weekly recaps for this pool. Opt-in: while off the pool is skipped entirely and no provider call is made for it."),
        ),
    ]
