# Generated by Django 5.2.16 on 2026-09-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pickem_api", "0100_poolsettings_ai_summaries_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesandscores",
            name="spread",
            field=models.FloatField(
                blank=True,
                help_text="Home team's own point spread, as ESPN sends it: negative favors the home team, positive favors the away team, 0 is a pick'em",
                null=True,
            ),
        ),
    ]
