# Generated by Django 5.2.16 on 2026-09-22 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0101_alter_gamesandscores_spread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('picks_open', 'Picks open'), ('picks_missed', 'Missed picks'), ('week_winner', 'Week winner'), ('season_winner', 'Season winner'), ('message_reply', 'Message reply'), ('family_invite', 'Family invite'), ('announcement', 'Announcement')], default='announcement', max_length=32)),
                ('title', models.CharField(help_text='The bold line in the panel', max_length=200)),
                ('body', models.CharField(blank=True, default='', help_text='Optional supporting line', max_length=500)),
                ('url', models.CharField(blank=True, default='', help_text='Already-resolved path this notification links to', max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='pickem_api.family')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='pickem_api.pool')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notification_recipient_idx')],
            },
        ),
    ]
