# Generated by Django 5.2.16 on 2026-09-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0103_alter_notification_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, default=None, help_text='Producer-set idempotency key; NULL when the row has no natural identity', max_length=200, null=True, unique=True),
        ),
    ]
