# Generated by Django 5.2.16 on 2026-09-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0104_notification_dedupe_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekWinnerAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('season', 'week'), name='unique_week_winner_announcement')],
            },
        ),
    ]
