# Generated by Django 5.2.16 on 2026-10-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickem_api', '0105_weekwinnerannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='idle_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='is_idle',
            field=models.BooleanField(default=False, help_text='No member made a manual pick in the last two completed weeks (stays set until someone picks)'),
        ),
    ]
