name: Publish Artifacts

on:
  push:
    branches:
      - main

jobs:
  get_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Get tag version"
        id: "tag"
        run: |
          RELEASE_VERSION=$(git describe --tags `git rev-list --tags --max-count=1` | awk 'BEGIN{FS=OFS="."} {$3+=1} 1' | sed 's/family-pickem-//')
          echo "${RELEASE_VERSION}-latest"
          echo "tag=${RELEASE_VERSION}-latest" >> "$GITHUB_OUTPUT"    

  publish_docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: get_tag
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/app/Dockerfile
          push: true
          tags: ${{needs.get_tag.outputs.tag}}

  publish_helm:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: get_tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Update Helm Tags
        run: |
          sed -i "s/0.0.0/${{needs.get_tag.outputs.tag}}/g" ./charts/family-pickem/Chart.yaml
          cat ./charts/family-pickem/Chart.yaml

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"