name: Pull Request Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r pickem/requirements.txt

      - name: Run tests
        run: cd pickem && python manage.py test --settings=pickem.test_settings --verbosity=2
